debug:
	cd client && make debug
	cd server && make debug
	cd gen && make debug

release:
	cd client && make release
	cd server && make release
	cd gen && make release

clean:
	cd client && make clean
	cd server && make clean
	cd gen && make clean
