debug:
	cd engine && make debug
	cd demogen && make debug
	cd mappng && make debug
	cd mapeditor && make debug
	cd slippymap && make debug

release:
	cd engine && make release
	cd demogen && make release
	cd mappng && make release
	cd mapeditor && make release
	cd slippymap && make release

clean:
	cd engine && make clean
	cd demogen && make clean
	cd mappng && make clean
	cd mapeditor && make clean
	cd slippymap && make clean
