debug:
	cd demo && make debug
	cd mappng && make debug
	cd mapeditor && make debug
	cd slippymap && make debug

release:
	cd demo && make release
	cd mappng && make release
	cd mapeditor && make release
	cd slippymap && make release

clean:
	cd demo && make clean
	cd mappng && make clean
	cd mapeditor && make clean
	cd slippymap && make clean
